"""
views.py — one renderer per dashboard page.

Design constraints:

* Streamlit is imported lazily inside each renderer, so importing
  :mod:`rts_forensics.dashboard.views` (and therefore
  :mod:`rts_forensics.dashboard`) works without Streamlit installed.
* Renderers only read the :class:`~rts_forensics.models.RunResult` produced by
  :func:`rts_forensics.pipeline.run_analysis` and, for exports, call the public
  exporter APIs ``rts_forensics.report.write_tables`` / ``plot_results`` /
  ``render_report`` and ``rts_forensics.gis.write_geopackage``; downloads are
  generated by exactly the same exporters as the CLI.
* Raw and frame-corrected series are always shown side by side.
* Movement concern and measurement reliability are rendered as separate
  sections; they are never merged into one grade.
* The map is drawn in the supplied Cartesian grid. No geographic basemap is
  requested, and none is drawn unless a site transform/CRS is configured.
"""

from __future__ import annotations

import tempfile
from collections.abc import Callable, Iterable
from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
#  Lazy Streamlit access and small display helpers
# ---------------------------------------------------------------------------


def _st() -> Any:
    """Import Streamlit at call time, never at module import time."""
    import streamlit as st

    return st


def _table(run: Any, name: str) -> Any:
    """Fetch a registered table by canonical name, or ``None``."""
    tables = getattr(run, "tables", None) or {}
    if name in tables:
        return tables[name]
    getter = _TABLE_GETTERS.get(name)
    return getter(run) if getter is not None else None


def _empty(table: Any) -> bool:
    return table is None or bool(getattr(table, "empty", True))


def _show_table(
    st: Any,
    table: Any,
    *,
    caption: str | None = None,
    message: str = "No rows are available for this table in the current run.",
    limit: int | None = 500,
) -> None:
    if caption:
        st.caption(caption)
    if _empty(table):
        st.info(message)
        return
    view = table.head(limit) if limit is not None else table
    st.dataframe(view, use_container_width=True)


def _filtered(table: Any, point_id: str) -> Any:
    if _empty(table) or "point_id" not in getattr(table, "columns", ()):
        return table
    return table[table["point_id"] == point_id]


def _point_ids(run: Any) -> list[str]:
    for name in ("prism_summary", "concern", "reliability", "frame_corrected", "displacements"):
        table = _table(run, name)
        if not _empty(table) and "point_id" in table.columns:
            return sorted(str(value) for value in table["point_id"].dropna().unique())
    observations = _table(run, "observations")
    if not _empty(observations) and "point_id" in observations.columns:
        return sorted(str(value) for value in observations["point_id"].dropna().unique())
    return []


def _exists(table: Any, *columns: str) -> bool:
    available = getattr(table, "columns", ())
    return not _empty(table) and all(column in available for column in columns)


def _chart_columns(table: Any, candidates: Iterable[str]) -> list[str]:
    available = getattr(table, "columns", ())
    return [column for column in candidates if column in available]


def _transform_configured(config: Any) -> bool:
    if config is None:
        return False
    gis_config = getattr(config, "gis", None)
    if gis_config is None:
        return False
    return bool(getattr(gis_config, "transform", None)) or bool(getattr(gis_config, "srs_wkt", None))


# ---------------------------------------------------------------------------
#  RunResult accessors (the run keeps both section objects and a table registry)
# ---------------------------------------------------------------------------


def _observations(run: Any) -> Any:
    return getattr(run, "observations", None)


def _cycle_table(run: Any) -> Any:
    cycles = getattr(run, "cycles", None)
    return getattr(cycles, "cycles", None)


def _segments(run: Any) -> Any:
    cycles = getattr(run, "cycles", None)
    return getattr(cycles, "segments", None)


def _candidate_events(run: Any) -> Any:
    cycles = getattr(run, "cycles", None)
    return getattr(cycles, "candidate_events", None)


def _prism_cycles(run: Any) -> Any:
    displacements = getattr(run, "displacements", None)
    return getattr(displacements, "prism_cycles", None)


def _baselines(run: Any) -> Any:
    displacements = getattr(run, "displacements", None)
    return getattr(displacements, "baselines", None)


def _displacements(run: Any) -> Any:
    displacements = getattr(run, "displacements", None)
    return getattr(displacements, "displacements", None)


def _noise_pooled(run: Any) -> Any:
    noise = getattr(run, "noise", None)
    return getattr(noise, "pooled", None)


def _noise_flags(run: Any) -> Any:
    noise = getattr(run, "noise", None)
    return getattr(noise, "flags", None)


def _frame_coefficients(run: Any) -> Any:
    frames = getattr(run, "frames", None)
    return getattr(frames, "coefficients", None)


def _frame_diagnostics(run: Any) -> Any:
    frames = getattr(run, "frames", None)
    return getattr(frames, "diagnostics", None)


def _frame_corrected(run: Any) -> Any:
    frames = getattr(run, "frames", None)
    return getattr(frames, "corrected", None)


def _frame_membership(run: Any) -> Any:
    frames = getattr(run, "frames", None)
    selection = getattr(frames, "membership", None)
    return getattr(selection, "diagnostics", None)


def _rates(run: Any) -> Any:
    rates = getattr(run, "rates", None)
    if not _empty(rates):
        return rates
    return _table_from_tables(run, "rates")


def _concern(run: Any) -> Any:
    classification = getattr(run, "classification", None)
    return getattr(classification, "concern", None)


def _reliability(run: Any) -> Any:
    classification = getattr(run, "classification", None)
    return getattr(classification, "reliability", None)


def _flags(run: Any) -> Any:
    classification = getattr(run, "classification", None)
    return getattr(classification, "flags", None)


def _summary(run: Any) -> Any:
    table = _table_from_tables(run, "prism_summary")
    if table is not None:
        return table
    return _table_from_tables(run, "summary")


def _table_from_tables(run: Any, name: str) -> Any:
    return (getattr(run, "tables", None) or {}).get(name)


_TABLE_GETTERS: dict[str, Callable[[Any], Any]] = {
    "observations": _observations,
    "prism_cycles": _prism_cycles,
    "baselines": _baselines,
    "displacements": _displacements,
    "segments": _segments,
    "processing_segments": _segments,
    "candidate_events": _candidate_events,
    "rates": _rates,
    "pooled_repeatability": _noise_pooled,
    "noise_pooled": _noise_pooled,
    "spikes": _noise_flags,
    "frame_cycles": _frame_coefficients,
    "frame_coefficients": _frame_coefficients,
    "frame_diagnostics": _frame_diagnostics,
    "frame_membership": _frame_membership,
    "frame_corrected": _frame_corrected,
    "timeseries_24h": lambda run: _table_from_tables(run, "timeseries_24h"),
    "concern": _concern,
    "reliability": _reliability,
    "flags": _flags,
    "prism_summary": _summary,
    "summary": _summary,
}


# ---------------------------------------------------------------------------
#  1. Upload & audit
# ---------------------------------------------------------------------------


def render_upload_audit(run: Any, *, config: Any = None, audit: Any = None) -> None:
    st = _st()
    st.subheader("Upload & audit")
    st.caption(
        "The original upload is never modified. Every derived row keeps its "
        "source SHA-256 and physical line number."
    )

    parsed = getattr(run, "parsed", None)
    sources = getattr(parsed, "sources", None) or []
    if sources:
        st.markdown("**Source files (original bytes and SHA-256)**")
        st.dataframe(
            [
                {
                    "name": source.name,
                    "sha256": source.sha256,
                    "bytes": source.n_bytes,
                    "rows": source.n_rows,
                }
                for source in sources
            ],
            use_container_width=True,
        )

    spec = getattr(parsed, "format", None)
    if spec is not None:
        st.markdown("**Detected format**")
        st.json(
            {
                "delimiter": spec.delimiter,
                "encoding": spec.encoding,
                "time_format": spec.time_format,
                "has_header": spec.has_header,
            }
        )

    diagnostics = getattr(parsed, "diagnostics", None)
    st.markdown("**Parser diagnostics**")
    _show_table(
        st,
        diagnostics,
        message="No parser diagnostics were recorded.",
    )

    observations = _observations(run)
    if not _empty(observations):
        st.markdown(f"**Canonical observations** ({len(observations):,} rows)")
        st.dataframe(observations.head(200), use_container_width=True)

    if audit is not None:
        summary = audit.summary() if hasattr(audit, "summary") else {}
        st.markdown("**Configuration audit**")
        st.json(summary)
        warnings = getattr(audit, "warnings", None) or []
        for warning in warnings:
            st.warning(warning)

    st.markdown("**Effective configuration**")
    if config is not None and hasattr(config, "to_dict"):
        st.json(config.to_dict())
    else:
        st.info("No configuration object is attached to this run.")


# ---------------------------------------------------------------------------
#  2. Station frame
# ---------------------------------------------------------------------------


def render_station_frame(run: Any, *, config: Any = None, audit: Any = None) -> None:
    st = _st()
    st.subheader("Station frame")
    st.caption(
        "Per-cycle frame reconstruction. Raw observations are never overwritten; "
        "the fitted correction is experimental and relative to the chosen network."
    )

    st.markdown("**Station cycles**")
    _show_table(
        st,
        _cycle_table(run),
        caption="Times, counts, station coordinates, orientation offset and scale.",
        message="No station cycle table is available.",
    )

    coefficients = _frame_coefficients(run)
    st.markdown("**Frame coefficients**")
    _show_table(
        st,
        coefficients,
        caption="Rotation/translation/scale/vertical terms with standard errors and rank.",
        message="Frame coefficients are not available (frame correction not configured or insufficient).",
    )

    if _exists(coefficients, "cycle_id", "rotation_arcsec"):
        st.markdown("**Rotation and translation through the record**")
        y_columns = _chart_columns(
            coefficients, ("rotation_arcsec", "tE_mm", "tN_mm", "scale_ppm")
        )
        if y_columns:
            st.line_chart(coefficients, x="cycle_id", y=y_columns)

    diagnostics = _frame_diagnostics(run)
    st.markdown("**Fit diagnostics (rank, conditioning, RMS)**")
    _show_table(st, diagnostics, message="No frame diagnostics are available.")

    membership = _frame_membership(run)
    st.markdown("**Frame membership and exclusions**")
    _show_table(
        st,
        membership,
        caption="Exclusions prevent a tested point from proving its own stability.",
        message="Frame membership is not published in this run.",
    )

    corrected = _frame_corrected(run)
    st.markdown("**Raw versus frame-corrected series**")
    if _exists(corrected, "los_raw_mm", "los_fc_mm"):
        pairs = _chart_columns(
            corrected,
            ("los_raw_mm", "los_fc_mm", "ver_raw_mm", "ver_fc_mm", "tan_raw_mm", "tan_fc_mm"),
        )
        st.caption(
            "Both raw and corrected columns are shown; the corrected series is "
            "experimental and must be read beside the raw one."
        )
        st.line_chart(corrected, x="cycle_id", y=pairs)
        st.dataframe(corrected.head(500), use_container_width=True)
    else:
        _show_table(st, corrected, message="No frame-corrected series is available.")


# ---------------------------------------------------------------------------
#  3. Prism explorer
# ---------------------------------------------------------------------------


def render_prism_explorer(run: Any, *, config: Any = None, audit: Any = None) -> None:
    st = _st()
    st.subheader("Prism explorer")
    point_ids = _point_ids(run)
    if not point_ids:
        st.info("No prism-cycle series are available in this run.")
        return

    point_id = st.selectbox("Prism", point_ids)
    concern = _filtered(_table(run, "concern"), point_id)
    reliability = _filtered(_table(run, "reliability"), point_id)

    left, right = st.columns(2)
    with left:
        st.markdown("**Movement concern (exploratory screening)**")
        _show_table(
            st,
            concern,
            message="No movement-concern row for this prism.",
            limit=100,
        )
    with right:
        st.markdown("**Measurement reliability (separate from concern)**")
        _show_table(
            st,
            reliability,
            message="No reliability row for this prism.",
            limit=100,
        )

    st.markdown("**Raw versus frame-corrected series**")
    corrected = _filtered(_table(run, "frame_corrected"), point_id)
    if _exists(corrected, "cycle_id", "los_raw_mm", "los_fc_mm"):
        y_columns = _chart_columns(
            corrected,
            ("los_raw_mm", "los_fc_mm", "ver_raw_mm", "ver_fc_mm", "tan_raw_mm", "tan_fc_mm"),
        )
        st.caption(
            "Frame correction is experimental and relative to the chosen network; "
            "raw and corrected series are plotted together, never one instead of the other."
        )
        st.line_chart(corrected, x="cycle_id", y=y_columns)
        st.dataframe(corrected, use_container_width=True)
    else:
        displacements = _filtered(_table(run, "displacements"), point_id)
        st.caption("Frame correction is not available for this run; raw products are shown.")
        _show_table(st, displacements, message="No displacement series for this prism.")

    st.markdown("**Rates (24 h block medians, backwards from the final record)**")
    rates = _filtered(_table(run, "rates"), point_id)
    _show_table(st, rates, message="No rate rows for this prism.")

    st.markdown("**Retained flags (never deleted)**")
    flags = _filtered(_table(run, "flags"), point_id)
    if _empty(flags):
        flags = _filtered(_table(run, "spikes"), point_id)
    _show_table(st, flags, message="No retained flags for this prism.")


# ---------------------------------------------------------------------------
#  4. Map
# ---------------------------------------------------------------------------


def _coordinate_table(run: Any) -> Any:
    for name in ("prism_summary", "prism_cycles", "observations"):
        table = _table(run, name)
        if _exists(table, "te_m", "tn_m"):
            return table
    return None


def render_map(run: Any, *, config: Any = None, audit: Any = None) -> None:
    st = _st()
    st.subheader("Map")
    st.caption(
        "Drawn in the supplied Cartesian grid. Easting/northing are processing "
        "coordinates and may be a shifted dummy grid; no CRS is inferred and no "
        "geographic basemap is requested."
    )

    coordinates = _coordinate_table(run)
    if coordinates is None:
        st.info("No coordinate table is available in this run.")
        return

    frame = coordinates.dropna(subset=["te_m", "tn_m"])
    summary = _table(run, "prism_summary")
    color = None
    if _exists(summary, "point_id", "final_class"):
        frame = frame.merge(
            summary[["point_id", "final_class"]],
            on="point_id",
            how="left",
        ) if "point_id" in frame.columns else frame
        color = "final_class"
    if color is not None and color in frame.columns:
        st.scatter_chart(frame, x="te_m", y="tn_m", color=color)
    else:
        st.scatter_chart(frame, x="te_m", y="tn_m")

    if _transform_configured(config):
        gis_config = config.gis
        st.info(
            "A site transform/CRS is configured: exported geometry (and vector "
            "components) follow it. The preview above stays in the input grid; "
            "no basemap is added."
        )
        st.json(
            {
                "srs_id": gis_config.srs_id,
                "srs_wkt": gis_config.srs_wkt,
                "transform": gis_config.transform,
            }
        )
    else:
        st.caption(
            "No transform/CRS is configured (srs_id -1, undefined Cartesian), so "
            "no basemap is drawn and none is implied."
        )

    show_vectors = st.checkbox("Show movement-vector attributes (if exported)")
    if show_vectors:
        vectors = _table(run, "movement_vectors")
        _show_table(
            st,
            vectors,
            caption="Vector role (raw / frame-corrected / artefact) and contributing interval are explicit.",
            message="Movement vectors are written to the GeoPackage download; no in-run vector table is registered.",
        )

    st.markdown("**Coordinates used for the plot**")
    st.dataframe(frame.head(2000), use_container_width=True)


# ---------------------------------------------------------------------------
#  5. Events & investigations
# ---------------------------------------------------------------------------


def render_events(run: Any, *, config: Any = None, audit: Any = None) -> None:
    st = _st()
    st.subheader("Events & investigations")
    st.caption(
        "Candidate events and investigation records. Every candidate carries "
        "competing explanations; correlation alone does not identify a resection "
        "reference."
    )

    forensics = getattr(run, "forensics", None)
    evidence = getattr(forensics, "evidence", None) or {}
    if evidence:
        families = list(evidence)
        tabs = st.tabs(families)
        for tab, family in zip(tabs, families, strict=True):
            with tab:
                _show_table(st, evidence[family], message=f"No evidence rows for {family}.")
    else:
        st.info("No forensic evidence tables are registered in this run.")

    investigations = getattr(forensics, "investigations", None)
    st.markdown("**Investigation register**")
    _show_table(st, investigations, message="No investigation records.")

    statuses = getattr(forensics, "statuses", None)
    st.markdown("**Test statuses (unavailable tests carry an explicit reason)**")
    _show_table(st, statuses, message="No per-test status table.")

    events = _table(run, "candidate_events")
    st.markdown("**Candidate frame events from cycle processing**")
    _show_table(st, events, message="No candidate frame events detected.")


# ---------------------------------------------------------------------------
#  6. Downloads
# ---------------------------------------------------------------------------


def render_downloads(run: Any, *, config: Any = None, audit: Any = None) -> None:
    st = _st()
    st.subheader("Downloads")
    st.caption(
        "Downloads are produced by the same exporters as the CLI: CSV tables, "
        "figures, report.md/report.html and the GeoPackage with its SHA-256 manifest."
    )

    if st.button("Prepare download bundle"):
        from rts_forensics import gis, report

        out_dir = Path(tempfile.mkdtemp(prefix="rts-forensics-"))
        try:
            report.write_tables(run, out_dir)
            report.plot_results(run, out_dir)
            report.render_report(run, out_dir)
            gis.write_geopackage(run, out_dir / "rts_forensics.gpkg", config=config)
        except Exception as exc:  # surface exporter errors in the UI, never crash the app
            st.error(f"Export failed: {exc}")
        else:
            st.session_state["rts_forensics_download_dir"] = str(out_dir)

    out_dir_value = (
        st.session_state["rts_forensics_download_dir"]
        if "rts_forensics_download_dir" in st.session_state
        else None
    )
    if not out_dir_value:
        st.info("Select 'Prepare download bundle' to generate the outputs.")
        return

    files = sorted(path for path in Path(out_dir_value).rglob("*") if path.is_file())
    if not files:
        st.warning("The exporter produced no files.")
        return
    for path in files:
        st.download_button(
            label=f"{path.relative_to(out_dir_value)} ({path.stat().st_size:,} bytes)",
            data=path.read_bytes(),
            file_name=path.name,
            key=f"download::{path}",
        )


# ---------------------------------------------------------------------------
#  Registry
# ---------------------------------------------------------------------------

#: Page key -> renderer. Keys must match :data:`rts_forensics.dashboard.PAGE_KEYS`.
PAGE_RENDERERS: dict[str, Callable[..., None]] = {
    "upload_audit": render_upload_audit,
    "station_frame": render_station_frame,
    "prism_explorer": render_prism_explorer,
    "map": render_map,
    "events": render_events,
    "downloads": render_downloads,
}

__all__ = [
    "PAGE_RENDERERS",
    "render_downloads",
    "render_events",
    "render_map",
    "render_prism_explorer",
    "render_station_frame",
    "render_upload_audit",
]
